GET https://node-do-zero-m5pb.onrender.com/videos

###
GET http://localhost:3000/videos

###
POST https://node-do-zero-m5pb.onrender.com/videos
Content-Type: application/json

{
    "title": "Video 01",
    "description": "Teste do vídeo 01",
    "duration": "190"
}

###
PUT https://node-do-zero-m5pb.onrender.com/videos/de80247b-6b10-47c6-b0c5-1198c08b4db0
Content-Type: application/json

{
    "title": "Vídeo 02",
    "description": "continua igual",
    "duration": 190
}

###
DELETE https://node-do-zero-m5pb.onrender.com/videos/860c0ac4-181c-4fbc-9b6a-ffd503f3929a